services:
  postgres:
    image: postgres:15-alpine
    container_name: unichat_db
    restart: always
    environment:
      POSTGRES_USER: unichat_user
      POSTGRES_PASSWORD: unichat_password
      POSTGRES_DB: unichat_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: